"""Cloudinary-backed Django storage for persistent production media.

The implementation uses Cloudinary's maintained official Python SDK rather
than the unmaintained third-party django-cloudinary-storage package. File
names remain Django storage keys, preserving the existing model schema.
"""

from __future__ import annotations

from typing import Any

import cloudinary
import cloudinary.api
import cloudinary.uploader
import cloudinary.utils
from django.core.files.storage import Storage


class CloudinaryMediaStorage(Storage):
    """Store validated admin-uploaded images and videos in Cloudinary.

    This storage is deliberately used only as Django's ``default`` storage in
    production. It never handles static files and does not support directory
    listing, preventing application code from accidentally enumerating an
    entire Cloudinary account.
    """

    is_cloudinary_storage = True

    def __init__(self, **options: Any) -> None:
        super().__init__()
        self.cloud_name = options["cloud_name"]
        self.api_key = options["api_key"]
        self.api_secret = options["api_secret"]
        cloudinary.config(
            cloud_name=self.cloud_name,
            api_key=self.api_key,
            api_secret=self.api_secret,
            secure=True,
        )

    @staticmethod
    def resource_type(name: str) -> str:
        """Map controlled upload namespaces to Cloudinary resource types."""
        return "video" if name.startswith("products/videos/") else "image"

    def _save(self, name: str, content: Any) -> str:
        """Upload a file with its server-generated storage key as public ID."""
        content.seek(0)
        cloudinary.uploader.upload(
            content,
            public_id=name,
            resource_type=self.resource_type(name),
            overwrite=False,
            unique_filename=False,
            use_filename=False,
        )
        return name

    def delete(self, name: str) -> None:
        if name:
            cloudinary.uploader.destroy(
                name,
                resource_type=self.resource_type(name),
                invalidate=True,
            )

    def exists(self, name: str) -> bool:
        if not name:
            return False
        try:
            cloudinary.api.resource(name, resource_type=self.resource_type(name))
        except Exception:
            return False
        return True

    def url(self, name: str) -> str:
        url, _ = cloudinary.utils.cloudinary_url(
            name,
            resource_type=self.resource_type(name),
            secure=True,
        )
        return url

    def size(self, name: str) -> int:
        resource = cloudinary.api.resource(name, resource_type=self.resource_type(name))
        return int(resource["bytes"])

    def get_available_name(self, name: str, max_length: int | None = None) -> str:
        """Names are UUID-generated by upload_to, so collision renaming is unsafe."""
        return name

    def get_modified_time(self, name: str):  # type: ignore[no-untyped-def]
        raise NotImplementedError("Cloudinary media does not expose filesystem timestamps.")

    def path(self, name: str) -> str:
        raise NotImplementedError("Cloudinary media has no local filesystem path.")


def cloudinary_transformed_url(name: str, width: int) -> str:
    """Return one of the fixed, CDN-cached responsive image delivery URLs."""
    url, _ = cloudinary.utils.cloudinary_url(
        name,
        resource_type="image",
        secure=True,
        width=width,
        crop="limit",
        fetch_format="auto",
        quality="auto",
    )
    return url
