# Generated by Django 6.0.8 on 2026-08-14 13:34

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AboutSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(default="Our Story", max_length=200)),
                ("subtitle", models.CharField(blank=True, max_length=300)),
                (
                    "story_text",
                    models.TextField(help_text="Brand history and craftsmanship narrative"),
                ),
                ("image", models.ImageField(blank=True, null=True, upload_to="about/")),
                ("is_active", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "About Section",
                "verbose_name_plural": "About Sections",
            },
        ),
        migrations.CreateModel(
            name="GalleryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("caption", models.CharField(blank=True, max_length=500)),
                ("image", models.ImageField(upload_to="gallery/%Y/%m/")),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("exhibition", "Exhibition"),
                            ("seminar", "Seminar"),
                            ("brand", "Brand Moment"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        default="exhibition",
                        max_length=30,
                    ),
                ),
                ("is_published", models.BooleanField(db_index=True, default=True)),
                (
                    "sort_priority",
                    models.PositiveIntegerField(
                        db_index=True, default=0, help_text="Lower values display first"
                    ),
                ),
                (
                    "event_date",
                    models.DateField(
                        blank=True, help_text="Date the exhibition or event took place", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "verbose_name": "Gallery Item",
                "verbose_name_plural": "Gallery Items",
                "ordering": ["sort_priority", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["is_published", "sort_priority", "-created_at"],
                        name="content_gal_is_publ_317cb5_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("customer_name", models.CharField(max_length=100)),
                ("review_text", models.TextField()),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        default=5, help_text="Customer rating from 1 to 5 stars"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Optional customer-approved photo",
                        null=True,
                        upload_to="reviews/%Y/%m/",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Controls public display on storefront",
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False, help_text="Flag indicating verified direct purchaser"
                    ),
                ),
                (
                    "sort_priority",
                    models.PositiveIntegerField(
                        db_index=True, default=0, help_text="Lower values display first"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "verbose_name": "Customer Review",
                "verbose_name_plural": "Customer Reviews",
                "ordering": ["sort_priority", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["is_published", "sort_priority", "-created_at"],
                        name="content_rev_is_publ_8c6b81_idx",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("rating__gte", 1), ("rating__lte", 5)),
                        name="check_review_rating_1_to_5",
                    )
                ],
            },
        ),
    ]
