# Generated by Django 6.0.8 on 2026-08-14 14:24

from django.db import migrations, models

import backend.apps.common.media


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aboutsection",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=backend.apps.common.media.SecureUploadPath("about"),
                validators=[backend.apps.common.media.validate_secure_image],
            ),
        ),
        migrations.AlterField(
            model_name="galleryitem",
            name="image",
            field=models.ImageField(
                upload_to=backend.apps.common.media.SecureUploadPath("gallery"),
                validators=[backend.apps.common.media.validate_secure_image],
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Optional customer-approved photo",
                null=True,
                upload_to=backend.apps.common.media.SecureUploadPath("reviews"),
                validators=[backend.apps.common.media.validate_secure_image],
            ),
        ),
    ]
