# Generated by Django 6.0.8 on 2026-08-14 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProductAttributeType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=120, unique=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Product Attribute Type",
                "verbose_name_plural": "Product Attribute Types",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=120, unique=True)),
                ("description", models.TextField(blank=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
                "ordering": ["sort_order", "name"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "sort_order"], name="catalog_cat_is_acti_100145_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ProductAttributeValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("value", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=120)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "attribute_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="values",
                        to="catalog.productattributetype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Attribute Value",
                "verbose_name_plural": "Product Attribute Values",
                "ordering": ["attribute_type", "sort_order", "value"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("short_description", models.CharField(blank=True, max_length=500)),
                ("description", models.TextField(blank=True)),
                (
                    "base_price",
                    models.DecimalField(
                        decimal_places=2, help_text="Authoritative base price in PKR", max_digits=12
                    ),
                ),
                (
                    "compare_at_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Optional original price in PKR for compare/strike-through display",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "stock_quantity",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Base inventory quantity when no variants are configured",
                    ),
                ),
                (
                    "availability_status",
                    models.CharField(
                        choices=[
                            ("in_stock", "In Stock"),
                            ("low_stock", "Low Stock"),
                            ("out_of_stock", "Out of Stock"),
                            ("coming_soon", "Coming Soon"),
                        ],
                        db_index=True,
                        default="in_stock",
                        max_length=20,
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        db_index=True, default=True, help_text="Controls storefront visibility"
                    ),
                ),
                (
                    "is_custom_order",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Indicates customizability via WhatsApp consultation",
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Highlights product on homepage featured section",
                    ),
                ),
                (
                    "is_new_arrival",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Highlights product on homepage new arrivals section",
                    ),
                ),
                (
                    "sort_priority",
                    models.PositiveIntegerField(
                        db_index=True, default=0, help_text="Lower values display first"
                    ),
                ),
                ("seo_title", models.CharField(blank=True, max_length=70)),
                ("seo_description", models.CharField(blank=True, max_length=160)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="catalog.category",
                    ),
                ),
                (
                    "attributes",
                    models.ManyToManyField(
                        blank=True, related_name="products", to="catalog.productattributevalue"
                    ),
                ),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
                "ordering": ["sort_priority", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("image", models.ImageField(upload_to="products/%Y/%m/")),
                ("alt_text", models.CharField(blank=True, max_length=255)),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False,
                        help_text="Flag indicating the primary hero image for catalog display",
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Image",
                "verbose_name_plural": "Product Images",
                "ordering": ["sort_order", "-is_primary", "id"],
            },
        ),
        migrations.CreateModel(
            name="ProductVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Variant label, e.g. 'Size 7 / Rose Gold'", max_length=100
                    ),
                ),
                ("sku", models.CharField(blank=True, max_length=50)),
                (
                    "price_override",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Optional variant-specific price override in PKR",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "stock_quantity",
                    models.PositiveIntegerField(
                        default=0, help_text="Stock quantity for this specific variant"
                    ),
                ),
                ("is_available", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Variant",
                "verbose_name_plural": "Product Variants",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="ProductVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "video_file",
                    models.FileField(
                        blank=True,
                        help_text="Uploaded product video file (MP4/WebM)",
                        null=True,
                        upload_to="products/videos/%Y/%m/",
                    ),
                ),
                (
                    "video_url",
                    models.URLField(
                        blank=True, help_text="Optional external video link or CDN stream URL"
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="video",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Video",
                "verbose_name_plural": "Product Videos",
            },
        ),
        migrations.AddConstraint(
            model_name="productattributevalue",
            constraint=models.UniqueConstraint(
                fields=("attribute_type", "slug"), name="unique_attribute_value_per_type"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["is_published", "category", "sort_priority"],
                name="catalog_pro_is_publ_0c45e5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["is_published", "is_featured", "sort_priority"],
                name="catalog_pro_is_publ_50bddf_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["is_published", "is_new_arrival", "-created_at"],
                name="catalog_pro_is_publ_68f527_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.CheckConstraint(
                condition=models.Q(("base_price__gte", 0)),
                name="check_product_base_price_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("compare_at_price__isnull", True),
                    ("compare_at_price__gte", 0),
                    _connector="OR",
                ),
                name="check_product_compare_at_price_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("compare_at_price__isnull", True),
                    ("compare_at_price__gt", models.F("base_price")),
                    _connector="OR",
                ),
                name="check_product_compare_at_gt_base_price",
            ),
        ),
        migrations.AddIndex(
            model_name="productimage",
            index=models.Index(
                fields=["product", "sort_order"], name="catalog_pro_product_4ee3b8_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="productimage",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_primary", True)),
                fields=("product",),
                name="unique_primary_image_per_product",
            ),
        ),
        migrations.AddConstraint(
            model_name="productvariant",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("price_override__isnull", True), ("price_override__gte", 0), _connector="OR"
                ),
                name="check_variant_price_override_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="productvariant",
            constraint=models.UniqueConstraint(
                fields=("product", "name"), name="unique_variant_name_per_product"
            ),
        ),
    ]
