# Generated by Django 6.0.8 on 2026-08-14 14:24

from django.db import migrations, models

import backend.apps.common.media


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(
                upload_to=backend.apps.common.media.SecureUploadPath("products/images"),
                validators=[backend.apps.common.media.validate_secure_image],
            ),
        ),
        migrations.AlterField(
            model_name="productvideo",
            name="video_file",
            field=models.FileField(
                blank=True,
                help_text="Uploaded product video file (MP4/WebM)",
                null=True,
                upload_to=backend.apps.common.media.SecureUploadPath("products/videos"),
                validators=[backend.apps.common.media.validate_secure_video],
            ),
        ),
    ]
