# Generated by Django 6.0.8 on 2026-08-14 13:34

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Popup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("image", models.ImageField(blank=True, null=True, upload_to="popups/%Y/%m/")),
                ("cta_label", models.CharField(blank=True, max_length=50)),
                ("cta_url", models.CharField(blank=True, max_length=255)),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=False, help_text="Master switch for popup display"
                    ),
                ),
                ("start_datetime", models.DateTimeField(blank=True, null=True)),
                ("end_datetime", models.DateTimeField(blank=True, null=True)),
                (
                    "delay_seconds",
                    models.PositiveIntegerField(
                        default=5,
                        help_text="Seconds to wait after page load before displaying popup",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Popup Announcement",
                "verbose_name_plural": "Popup Announcements",
                "ordering": ["-created_at"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("start_datetime__isnull", True),
                            ("end_datetime__isnull", True),
                            ("end_datetime__gt", models.F("start_datetime")),
                            _connector="OR",
                        ),
                        name="check_popup_end_after_start",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Promotion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("subtitle", models.CharField(blank=True, max_length=300)),
                (
                    "announcement_text",
                    models.CharField(
                        blank=True,
                        help_text="Short message for top announcement bar (e.g. 'Eid Mubarak Sale: Free Shipping above PKR 5,000')",
                        max_length=255,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Optional campaign banner image",
                        null=True,
                        upload_to="promotions/%Y/%m/",
                    ),
                ),
                ("cta_label", models.CharField(blank=True, max_length=50)),
                ("cta_url", models.CharField(blank=True, max_length=255)),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Master active switch for this promotion",
                    ),
                ),
                (
                    "show_in_announcement_bar",
                    models.BooleanField(
                        default=True, help_text="Display announcement_text in top bar when active"
                    ),
                ),
                (
                    "start_datetime",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Optional scheduled activation datetime",
                        null=True,
                    ),
                ),
                (
                    "end_datetime",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Optional scheduled expiration datetime",
                        null=True,
                    ),
                ),
                (
                    "priority",
                    models.PositiveIntegerField(
                        db_index=True, default=0, help_text="Lower values take precedence"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Promotion",
                "verbose_name_plural": "Promotions",
                "ordering": ["priority", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "start_datetime", "end_datetime", "priority"],
                        name="promotions__is_acti_60c458_idx",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("start_datetime__isnull", True),
                            ("end_datetime__isnull", True),
                            ("end_datetime__gt", models.F("start_datetime")),
                            _connector="OR",
                        ),
                        name="check_promotion_end_after_start",
                    )
                ],
            },
        ),
    ]
