# Generated by Django 6.0.8 on 2026-08-14 14:24

from django.db import migrations, models

import backend.apps.common.media


class Migration(migrations.Migration):
    dependencies = [
        ("promotions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="popup",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=backend.apps.common.media.SecureUploadPath("popups"),
                validators=[backend.apps.common.media.validate_secure_image],
            ),
        ),
        migrations.AlterField(
            model_name="promotion",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Optional campaign banner image",
                null=True,
                upload_to=backend.apps.common.media.SecureUploadPath("promotions"),
                validators=[backend.apps.common.media.validate_secure_image],
            ),
        ),
    ]
