# Generated by Django 6.0.8 on 2026-08-14 13:34

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DeliverySettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "singleton_guard",
                    models.PositiveSmallIntegerField(
                        default=1, editable=False, help_text="Enforces single database record"
                    ),
                ),
                (
                    "pakistan_delivery_enabled",
                    models.BooleanField(
                        default=True, help_text="Enable delivery anywhere in Pakistan"
                    ),
                ),
                (
                    "free_delivery_threshold",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("5000.00"),
                        help_text="Subtotal threshold in PKR for free Pakistan delivery",
                        max_digits=12,
                    ),
                ),
                (
                    "pakistan_delivery_charge",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("250.00"),
                        help_text="Standard Pakistan delivery fee in PKR",
                        max_digits=12,
                    ),
                ),
                (
                    "international_delivery_mode",
                    models.CharField(
                        choices=[
                            ("disabled", "Disabled"),
                            ("whatsapp_quote", "Quote on WhatsApp"),
                            ("fixed", "Fixed Rate"),
                        ],
                        default="whatsapp_quote",
                        help_text="International order handling strategy",
                        max_length=20,
                    ),
                ),
                (
                    "international_delivery_fixed_charge",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Fixed international shipping fee if fixed rate mode is selected",
                        max_digits=12,
                        null=True,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Delivery Settings",
                "verbose_name_plural": "Delivery Settings",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("singleton_guard",), name="unique_delivery_settings_singleton"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("singleton_guard", 1)),
                        name="check_delivery_settings_singleton_guard_is_one",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("free_delivery_threshold__gte", 0)),
                        name="check_delivery_free_threshold_non_negative",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("pakistan_delivery_charge__gte", 0)),
                        name="check_delivery_pakistan_charge_non_negative",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("international_delivery_fixed_charge__isnull", True),
                            ("international_delivery_fixed_charge__gte", 0),
                            _connector="OR",
                        ),
                        name="check_delivery_intl_charge_non_negative",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "singleton_guard",
                    models.PositiveSmallIntegerField(
                        default=1, editable=False, help_text="Enforces single database record"
                    ),
                ),
                ("brand_name", models.CharField(default="Jewellery Brand", max_length=100)),
                ("tagline", models.CharField(blank=True, max_length=200)),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("contact_phone", models.CharField(blank=True, max_length=30)),
                (
                    "whatsapp_number",
                    models.CharField(
                        help_text="Normalized business WhatsApp number for orders, e.g. '+923001234567'",
                        max_length=30,
                    ),
                ),
                (
                    "canonical_site_url",
                    models.URLField(
                        blank=True,
                        help_text="Canonical storefront URL (e.g. 'https://www.example.com')",
                    ),
                ),
                ("default_seo_title", models.CharField(blank=True, max_length=70)),
                ("default_seo_description", models.CharField(blank=True, max_length=160)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Site Settings",
                "verbose_name_plural": "Site Settings",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("singleton_guard",), name="unique_site_settings_singleton"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("singleton_guard", 1)),
                        name="check_site_settings_singleton_guard_is_one",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SocialLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        help_text="Platform identifier, e.g. 'Instagram', 'Facebook', 'TikTok', 'WhatsApp'",
                        max_length=50,
                    ),
                ),
                ("url", models.URLField(help_text="Full profile or contact URL")),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Social Link",
                "verbose_name_plural": "Social Links",
                "ordering": ["sort_order", "platform"],
                "constraints": [
                    models.UniqueConstraint(fields=("platform",), name="unique_social_platform")
                ],
            },
        ),
    ]
